# 项目相关配置
make:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/make/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8085
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，从1000增加到2000
    accept-count: 2000
    threads:
      # tomcat最大线程数，从800增加到1000
      max: 1000
      # Tomcat启动初始化的线程数，从100增加到200
      min-spare: 200

# 日志配置
logging:
  level:
    com.make: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# 监控配置
monitor:
  server:
    info:
      expireTime: 300

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 115.190.121.53
    # 端口，默认为6379
    port: 6989
    # 数据库索引
    database: 0
    # 密码
    password: aB3x9Rq7Z2pY8sK4nL6
    # 连接超时时间 从10s增加到30s
    timeout: 60s
    lettuce:
      pool:
        # 连接池中的最小空闲连接 从0增加到2
        min-idle: 2
        # 连接池中的最大空闲连接 从8增加到16
        max-idle: 16
        # 连接池的最大数据库连接数 从8增加到32
        max-active: 128
        # 连接池最大阻塞等待时间 从-1ms改为30s
        max-wait: 60s
  # Quartz配置
  quartz:
    bootstrapEnabled: true
    bootstrapUseRedisLock: true
    bootstrapLockKey: "mq:bootstrap:lock"
    bootstrapLockTtlSeconds: 60
    bootstrapRetryTimes: 10
    bootstrapRetryIntervalMs: 3000

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.make.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /prod-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/finance/*,/stock/*,/flowable/*
# flowable相关表
flowable:
  # true 会对数据库中所有表进行更新操作。如果表不存在，则自动创建(建议开发时使用)
  database-schema-update: false
  # 关闭定时任务JOB
  async-executor-activate: false
python:
  script:
    path: python
    nexusStock:
      nodeId: 2
watchStockExecutor:
  corePoolSize": 10
  maxPoolSize: 10
